### ISSUE TITLE
Update B.io to Have One set of Examples as "Ballerina By Examples"

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3084]
**Description:**
Need to remove the 2 BBE views that we currently have on B.io as "Reference By Examples" and "Learn By Examples" and do the following.

- [x] Remove the Learn By Examples view.
- [x] Rename the Reference By Examples view to Ballerina By Examples
- [x] The URL structure of the Ballerina By Examples will be kept as `/learn/by-example` (i.e., what we had before).
- [x] Keep Ballerina-by-examples in the references section on the learn page.
- [x] Remove the URL property added in the `philosophy.js` file.
- [x] Fix the template of the BBE Tool via ballerina-platform/ballerina-release#1483.
- [x] Rename "Ballerina By Examples" to "Ballerina By Example" on the templates via ballerina-platform/ballerina-release#1483.
- [x] Update the layout of the BBE template to `ballerina-example-page-old` via ballerina-platform/ballerina-release#1483.
- [x] Add the breadcrumbs on the BBE view.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
The BBE Tool is fixed via https://github.com/ballerina-platform/ballerina-release/pull/1483.

**Comment by praneesha** [comment]
Closing since this is done now.
