### ISSUE TITLE
Redesign the Bio Community Page

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3195]
**Description:**
Need to do the improvements below to the B.io Community page.
- [ ] Redesign the community page
- [ ] Create the sub-pages of the Community page (e.g., events, community call etc.)
- [ ] Address the feedback in https://github.com/ballerina-platform/ballerina-dev-website/issues/2967
- [ ] Address the feedback in https://github.com/ballerina-platform/ballerina-dev-website/issues/2968
- [ ] Move the Language Walkthrough to the Community Page.
- [ ] Rename Community Call to Tech Talk.
- [ ] Work on https://github.com/ballerina-platform/ballerina-dev-website/issues/2892.
- [ ] Add a "Contact Us" section as per https://github.com/ballerina-platform/ballerina-dev-website/issues/3149.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing as this is done in [1] now.

[1] http://dev.ballerina.io/community/
