### ISSUE TITLE
Improve the Learn Page for the Swan Lake GA Release

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3205]
**Description:**
Need to do the below to improve the Home page for the Swan Lake GA release.

- [ ] Remove “Why Ballerina” from the Learn page via https://github.com/ballerina-platform/ballerina-dev-website/issues/3213.
- [ ] Remove the "Language Walkthrough" from the Learn page. Add it to the Community page via https://github.com/ballerina-platform/ballerina-dev-website/issues/3195.
- [ ] Remove the "Language Introduction" from learn and move it to the Community Page via https://github.com/ballerina-platform/ballerina-dev-website/issues/3195.

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing since there are individual issues created to track all the action items above.
