### ISSUE TITLE
Change All Titles and UI Labels to Sentence Case

### ISSUE THREAD

**Issue by praneesha** [ballerina-platform/ballerina-dev-website#3920]
**Description:**
Need to do this is all the doc components via the below.

- [x] [Lang Lib module descriptions (`module.md` file) do not have titles in them.](https://github.com/ballerina-platform/ballerina-dev-website/issues/3919)
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3918
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3917
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3916
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/3915
- [x] ballerina-platform/ballerina-standard-library#2748
- [x] [Change titles in the Blog](https://github.com/ballerina-platform/blog/pull/109)
- [x] [Change UI labels in API Docs](https://github.com/wso2-enterprise/ballerina-central/issues/643)
- [x] https://github.com/ballerina-platform/ballerina-dev-website/issues/4015

**Describe your task(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by praneesha** [comment]
Closing as all the sub tasks of this are done now.
